---
# tasks file for ansible-role-hp-serial

  - include: redhat.yml
    when: ansible_os_family == "RedHat" and ansible_system_vendor == "HP"

  - include: redhat.yml
    when: ansible_os_family == "RedHat" and ansible_system_vendor == "Dell"
