---
# tasks file for ansible-role-serial

- include_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_connection != 'chroot'
    - ansible_system_vendor == "HP" or ansible_system_vendor == "Dell Inc."
